# Generated by Django 4.2.6 on 2023-10-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('imc', models.FloatField()),
                ('fecha_nac', models.DateField()),
                ('passwrd', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('duracion', models.CharField(max_length=20)),
                ('beneficio', models.TextField()),
            ],
        ),
    ]
