# Generated by Django 4.2.6 on 2023-11-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.FloatField(),
        ),
    ]
