# Generated by Django 4.2.2 on 2023-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_cliente_plan_actual_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='informe_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='video_url',
            field=models.TextField(blank=True, help_text='Ingresa las urls de los videos', null=True),
        ),
    ]
