# Generated by Django 4.2.2 on 2023-11-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_plan_informe_url_plan_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='video_url',
            new_name='videos_urls',
        ),
    ]
