# Generated by Django 4.2.2 on 2023-11-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_video_url_plan_videos_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='videos_urls',
        ),
        migrations.AddField(
            model_name='plan',
            name='es_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='url_streaming',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='videos_semanales',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
